### PR TITLE
Only set invisible cursor attribute if both curses and the terminal supp...

### PR DESCRIPTION
**Pull request by jahrome**
...ort it.

### CODE REVIEW

**Comment by firecat53** [comment]
I think this could be simplified to:

    try:
 		curses.curs_set(False)
    except AttributeError:
        pass 

Do you have an example of a terminal that doesn't support that attribute? I tried the xfce4-terminal and it is supported.

Thanks for the interest!
Scott

**Comment by jahrome** [comment]
I actually use xfce4-terminal and I get the error. Dunno why...

```
Traceback (most recent call last):
  File "/usr/bin/tabview", line 42, in <module>
    view(args.filename, enc=args.encoding)
  File "/usr/lib/python2.7/site-packages/tabview/tabview.py", line 716, in view
    curses.wrapper(main, d)
  File "/usr/lib/python2.7/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, *args, **kwds)
  File "/usr/lib/python2.7/site-packages/tabview/tabview.py", line 687, in main
    curses.curs_set(False)
_curses.error: curs_set() returned ERR
```

**Comment by firecat53** [comment]
Well, I can't reproduce this (Arch, xfce-terminal, python 2.7), but I went ahead and pushed the fix.

**Comment by wavexx** [comment]
I'm still not convinced about this. I also tested xfce-terminal, and it works as intended.
Is ncurses-terminfo correctly installed on your system?

A terminal which doesn't support this feature is the classic 'vt100'.
If we assume that the baseline term is 'vt100', use_default_colors() also fails.

**Comment by jahrome** [comment]
I have ncurses 5.9-7 but can't find ncurses-terminfo package (arch).

**Pull request closed without merging**
