### PR TITLE
Fixes #98

### LINKED ISSUE #98: Take into account double-width characters for column width calculations
Previous discussion for this in #54 an #92.

### PR DESCRIPTION
**Pull request by wavexx**

### CODE REVIEW

**Comment by firecat53** [comment]
Cool...I can't try it right now, but would you be able to run some timed sessions on big files and make sure there's not a significant performance hit? Thanks!

**Comment by firecat53** [comment]
No big changes on time...thanks! Merging

**Comment by firecat53** [comment]
Ooops. Well, I was in a hurry and checked the timing wrong. It _substantially_ increases the time to calculate column_widths for big files. 

a 36MB file went from ~2.5 sec startup time to over 15 sec.
a 280MB file went from 14 sec to almost 2 minutes.

I wonder if perhaps a switch could be set to turn on this calculation if you know you'll be dealing with double-width characters.

Thoughts?

**Comment by wavexx** [comment]
On 02/07/2015 09:40 PM, Scott Hansen wrote:
> Ooops. Well, I was in a hurry and checked the timing wrong. It
> _substantially_ increases the time to calculate column_widths for big
> files.

Yes, it does...

In fact, the redrawing performance also substantially suffers as I
initially wrote in the PR, although since you only see a small subset of
the data at once, it's not that noticeable in that case.

> I wonder if perhaps a switch could be set to turn on this calculation
> if you know you'll be dealing with double-width characters.
> 
> Thoughts?

That was my ideal doubt. There's no "quick" way to check if the incoming
file has double-width characters.

You can exclude the check for some encodings, but it hardly matters
since we're dealing with utf-8 most of the times.

A quick solution would be a command-line flag (--double_width).
A better solution would be cython (but it's an annoying dependency!).

**Comment by wavexx** [comment]
What about PR #103 for some middle ground approach.
I settled on 65k cells just by fiddling with timings.

**Pull request merged**
