### PR TITLE
Simplify drawing, remove redundand calls, handle truncated columns.

### PR DESCRIPTION
**Pull request by wavexx**
This code handles uniformly the last truncated column and/or the main column if the terminal width < column_width (which is something that will happen with large column widths). I also removed a lot of redundant ncurses calls.

### CODE REVIEW

**Comment by wavexx** [comment]
I'm trying a few things in this branch to maximize data real-estate. I'm not sure if that's a good idea yet, but I'm using it to get a feel. I've tried to remove the divider line and use the underline style instead, though maybe using the reverse style for the header (if available) would be nicer looking...

I was also thinking that the best place for the interactive prompt is on info bar at the top: just move the cursor and re-enable the blinking while doing insertion.

**Comment by firecat53** [comment]
I would prefer to keep the defaults to be a more readable and pleasant looking display and then have either command line or keybindings to change options for a denser display.

You've mentioned an 'interactive prompt' a couple of times. What do you see as the use cases for it? I'm just a little concerned about adding too much complexity :) 

Thanks for all your work on this!! Sorry I've been a little out of touch the past few days.

**Comment by wavexx** [comment]
On 01/02/2015 08:13 PM, Scott Hansen wrote:
> I would prefer to keep the defaults to be a more readable and
> pleasant looking display and then have either command line or
> keybindings to change options for a denser display.

Did you give the branch a try?

I'm not terribly satisfied by the underline, but the extra line is an
easy sell for me ;)

At any rate, the first commit should be ok, it just requires a larger
column_gap for the previous default. The drawing code is simpler as
well, and should be easier to extend for a variable column width.

> You've mentioned an 'interactive prompt' a couple of times. What do
> you see as the use cases for it? I'm just a little concerned about
> adding too much complexity :)

I really like the compact "minibuffer-style" prompts, since they don't
hide the data. For instance, when searching, you can start writing while
looking at previous cell contents and/or do something like incremental
search.

> Thanks for all your work on this!! Sorry I've been a little out of
> touch the past few days.

I'm having fun with it right now, as I can finally ditch ": set ts" for
viewing tabular data.

Though it's slower... the pure-python approach doesn't cut it for
multi-megabyte tables :(

**Comment by firecat53** [comment]
> I really like the compact "minibuffer-style" prompts, since they don't hide the data. For instance, when searching, you can start writing while looking at previous cell contents and/or do something like incremental search.

Ah, so you're thinking of having the search prompt perhaps where the data is currently displayed at the top?

> Though it's slower... the pure-python approach doesn't cut it for multi-megabyte tables :(

I dunno...I can open a 280MB file in about 10 sec (i5 laptop). Once it's open, browsing isn't slowed down at all. Even a full 'natural sort' only takes a few seconds.

**Comment by firecat53** [comment]
I'm thinking instead of using a command line switch to set column width/gap of defining a few new keybindings to do it dynamically:

< > increase/decrease column width
- + increase/decrease column gap

Any thoughts or other suggestions on that?

**Comment by wavexx** [comment]
On 01/03/2015 01:44 AM, Scott Hansen wrote:
>> I really like the compact "minibuffer-style" prompts, since they
>> don't hide the data. For instance, when searching, you can start
>> writing while looking at previous cell contents and/or do something
>> like incremental search.
> 
> Ah, so you're thinking of having the search prompt perhaps where the
> data is currently displayed at the top?

Yes. When a prompt is needed, just reuse the same space.

It would come in handy for asking basic stuff like "column width", or an
interactive "goto X,Y".

>> Though it's slower... the pure-python approach doesn't cut it for
>> multi-megabyte tables :(
> 
> I dunno...I can open a 280MB file in about 10 sec (i5 laptop). Once
> it's open, browsing isn't slowed down at all. Even a full 'natural
> sort' only takes a few seconds.

I'm working with genetic allelic data with 1m rows and ~5k columns.
These are usually narrow columns of 2/3 characters only, so changing the
gap to 2 characters wastes a lot of screen space.

Parsing is indeed probably what takes most of the time, and that's also
why I was investigating the ability to use the pandas I/O functions to
speedup the loading.

Though vim is still faster opening these files.

**Comment by wavexx** [comment]
On 01/03/2015 01:46 AM, Scott Hansen wrote:
> I'm thinking instead of using a command line switch to set column
> width/gap of defining a few new keybindings to do it dynamically:
> 
> < > increase/decrease column width
> - + increase/decrease column gap
> 
> Any thoughts or other suggestions on that?

Allow the gap to go to 0. It's rare, but I would have a few use cases
for that. +1/-1 increments would be good.

For <> (column size), I would chose something proportional instead (+/-
10%).

**Pull request closed without merging**
