### PR TITLE
Implement variable width columns

### PR DESCRIPTION
**Pull request by jahrome**

### CODE REVIEW

**Comment by jahrome** [comment]
When this patch will be merged, I'd also like to discuss the implementation of other functionalities like the ability to hide columns and filters on rows to do some sort of data mining (I have pending patches for both).

**Comment by firecat53** [comment]
Ok, I'm working through your pull request now.

FYI, I made a mistake with the list(range(xxx)). I was going too fast that morning and forgot that since the result of the range was being used as an iterator already, the list() call was unncessary. It would only be necessary in a Py3 implementation where the result was to be immediately used/indexed.

**Comment by firecat53** [comment]
Check out latest changes in branch 'jahrome-variable_width_try2'.

That with statement in recalculate_layout is a bear to wade through!! It works, but any ideas on how make it more readable? I still can't figure out where the -3 comes into play...  :)

**Comment by jahrome** [comment]
Nice that you moved the column login into Viewer class, I was about to do it ! Few comments:
- I kept the -3 since it was specified like that in the original code ; it can safely be removed.
- Regarding the curs_set exception, it doesn't throw AttributeError but "_curses.error: curs_set() returned ERR" so need to catch Exception.
- Regarding 'mode' based calculation, I need to be able to disable it since I am far more comfortable with my logic (display full width unless overlong line) when I need to spot one unusual sized data among regular ones. Is it something we can set as an option ?

**Comment by wavexx** [comment]
On 01/21/2015 08:24 AM, Jerome Marty wrote:
> - I kept the -3 since it was specified like that in the original code
> ; it can safely be removed.

The - 3 was there to avoid showing truncated columns with just one
visible character + truncation mark.

**Comment by firecat53** [comment]
More updates to 'jahrome-variable_width_try2'. See issue #85 for comments.

**Comment by jahrome** [comment]
Looks good to me, thanks !

**Pull request closed without merging**
