### PR TITLE
TextBox implementation

### PR DESCRIPTION
**Pull request by gurisko**
This is intended to be a new class where we can implement basic editing for show_cell.
The main feature is the support of scrolling and it draws the window as suggested in #38

### CODE REVIEW

**Comment by gurisko** [comment]
This is still **experimental** and the question is if we want to write this from scratch. But now also `Search` can be implemented using `TextBox`:
```python
win = TextBox(self.scr, title="Search", editable=True)
win.run()
search = win.get_data().lower()
```

**Comment by wavexx** [comment]
I tried to use curses's TextPad (see the fix_search PR), which is the closest thing I could find already implemented in curses.

TextPad is so limited, I would rather go with this implementation. @firecat53 
had some alternative implementation coming from another project, if I recall correctly.

**Comment by gurisko** [comment]
@firecat53 what do you think about this?

**Comment by firecat53** [comment]
Sorry man, I didn't mean to ignore you! I did a project a couple of years ago, py_curses_editor, that I've been fixing up and getting ready to use for tabview. It already has most of the editing capabilities baked in that we would need. Feel free to take a look...I'm working now on refactoring/simplifying the code (it's always rough going back and seeing your old code!).

**Comment by gurisko** [comment]
@firecat53 haha, ok no problem. I just wanted to state that it should work and I am not going to commit more changes here. Feel free to accept/decline. ;)

**Comment by firecat53** [comment]
I appreciate your efforts and I still may borrow some of your code! :-)

**Comment by firecat53** [comment]
I've pushed a test branch 'editor' that uses my py_curses_editor project (you can install from pypi) for the popups and to test basic cell editing (no save feature yet). Let me know what you think.

**Comment by firecat53** [comment]
Thanks for the code! Included in part in 1.4.0.

**Pull request closed without merging**
