### PR TITLE
Double width chars

### LINKED ISSUE #54: Improve Unicode support
This file opens, but has some visual artifacts and inconsistent formatting:

http://www.i18nguy.com/unicode/unicode-example-utf8.zip

Edit: fails completely with python 2.x

### PR DESCRIPTION
**Pull request by wavexx**
It works, and should fix #54, but with an atrocious performance hit.

### CODE REVIEW

**Comment by wavexx** [comment]
Rebased on current master, though column_xw seems to return broken values since the last time I tried the branch, resulting in crashes.

**Comment by wavexx** [comment]
I'm not sure why travis fails here. The tests run on my machine, except for python 2.7 (for which I see there's no support yet).

**Comment by wavexx** [comment]
If we merge this, calculation of column widths should probably also consider double-width chars(!).

**Comment by firecat53** [comment]
I fixed the python 2 unittest...it was a stupid mistake. I rebased onto master with the fixed test and fixed support for command line object (list of lists) display. 

Some timing runs with a relatively big (280M) file didn't seem to show any significant difference between current master and this branch.

I haven't had a chance to work on adding in the double-width consideration in column width calculations yet.

Pushed to wavexx-double_width_chars branch.

**Comment by firecat53** [comment]
I think I'm going to merge this as-is and then open a separate issue for considering double-width characters in the column width calculations.

**Pull request closed without merging**
