### PR TITLE
Add C-a/C-e as alternatives to line_home/line_end

### PR DESCRIPTION
**Pull request by wavexx**
I'm not against adding some common bindings.
C-a/C-e are just aliases for line_home/line_end. Why not?

There's no other common emacs-like binding we could directly map right now (C-s/C-r do not map really well, and C-SPC (for mark) would have no "C-x C-x" (for jump to mark).

### CODE REVIEW

**Comment by firecat53** [comment]
Heh...looks like the byte string probably failed the python 2 test :)

**Comment by wavexx** [comment]
On 02/06/2015 06:09 PM, Scott Hansen wrote:
> Heh...looks like the byte string probably failed the python 2 test :)

Annoying.. :/

**Comment by firecat53** [comment]
Actually failed python 3...

    TypeError: unsupported operand type(s) for &: 'bytes' and 'int'

**Comment by wavexx** [comment]
On 02/06/2015 06:13 PM, Scott Hansen wrote:
> Actually failed python 3...
> 
>     TypeError: unsupported operand type(s) for &: 'bytes' and 'int'

I added a small CTRL() wrapper, which incidentally makes the code more
readable.

curses in python 2.7 doesn't really like unicode_literals, but I'd
rather not turn it off.

**Comment by firecat53** [comment]
Nice work :) Although Ctrl-a isn't that useful for me...it's my tmux prefix!

**Comment by gurisko** [comment]
@wavexx @firecat53 Thanks!

**Pull request closed without merging**
