### PR TITLE
Update tabview.py to support Pandas

### PR DESCRIPTION
**Pull request by scls19fr**
Update tabview.py to support Pandas DataFrame, Series and Panel

    import tabview.tabview as t

    import pandas as pd
    import pandas.io.data as web
    import datetime
    start = datetime.datetime(2010, 1, 1)
    end = datetime.datetime(2013, 1, 27)
    panel = web.DataReader(["F", "YHOO"], 'yahoo', start, end) # Panel
    df = panel.loc[:,:,"F"] # DataFrame
    ts=df['Adj Close'] # Series

    t.view(df)
    t.view(ts)
    t.view(panel)

See https://github.com/firecat53/tabview/issues/43

### CODE REVIEW

**Comment by wavexx** [comment]
I'm not sure it's a good idea to do this here, at least not this way.
Since the final structure is still a list of lists, there's no advantage in putting this code into tabview. You would end up adding specialized code for each python library.

It *would* make sense to use an NDArray as the data backing. This would avoid some internal conversions in DataFrame (though not always - since adding back the index rebuilds the NDArray anyway!).

I also see the same double transpose I commented on the Pandas issue.

**Comment by scls19fr** [comment]
My opinion was that some "pagers" will only be able to manage "flat" data (like `tabview`), some others (which doesn't exists, at least for now) may be able to managed hierarchical index (or hierarchical columns...). So putting this in Pandas will reduce "quality" of data that new pager could get.

About double transpose, I thought about the famous phrase of Don Knuth "Premature optimization is the root of all evil".

Moreover I think that my idea of defining a pd.view which links to tabview.tabview.view will allow easily monkey patching for other "pagers" to take place.

But I may be wrong. This PR was just for me a kind of reminder to remember my own modifications of tabview before something stable appears.

**Comment by wavexx** [comment]
On 01/05/2015 07:54 PM, scls19fr wrote:
> My opinion was that some "pagers" will only be able to manage "flat"
> data (like `tabview`), some others (which doesn't exists, at least
> for now) may be able to managed hierarchical index (or hierarchical
> columns...). So putting this in Pandas will reduce "quality" of data
> that new pager could get.

This is true, I agree with that.

> About double transpose, I thought about the famous phrase of Don
> Knuth "Premature optimization is the root of all evil".

More than optimization, there's no way a double transposition can be
fast. It's also unclear that you do that to remove the index and put the
columns as part of the data.

> Moreover I think that my idea of defining a pd.view which links to
> tabview.tabview.view will allow easily monkey patching for other
> "pagers" to take place.

Also true, I understood that from you PD comment.

Though you cannot expect that each pager includes the code to transform
the data as a list.

I would see two methods here:

- pd.view() : receives the pd objects directly
- pd.view_list() : generic list viewer

We could implement a view() method in each pd object
(DataFrame/Series/..) just calling pd.view(self)

pd.view would just be a simple function to convert the data to a generic
list and call pd.view_list.

pd.view_list would be initially aliased to tabview.view.

This would allow a pager to plug at either the list level, or implement
a more optimized method.

Any comment on this?

I cannot see a way to implement this using just one function and asking
each pager to implement the basic stuff. Annoying.

**Comment by scls19fr** [comment]
I like this idea of `pd.view` and `pd.view_list` but I'm not a Pandas maintainer.

**Comment by wavexx** [comment]
On 01/05/2015 08:28 PM, scls19fr wrote:
> I like this idea of `pd.view` and `pd.view_list` but I'm not a Pandas
> maintainer.

What about the actual usage?

There are a few things I would expect when calling view:

The signature should be

  view(data, index=None, **kwargs)

**kwargs is needed to implement an extensible wrapper.
I would define some mandatory stuff the pager should have.

I see:

- index=None = auto-detect
  index=True = include the index
  index=False = hide the index

- start=(0,0) = starting cursor position (very useful for debugging data)

Other stuff that we should consider for the documentation?

**Comment by wavexx** [comment]
On 01/05/2015 08:49 PM, Yuri D'Elia wrote:
> The signature should be
>   view(data, index=None, **kwargs)
> 
> **kwargs is needed to implement an extensible wrapper.
> I would define some mandatory stuff the pager should have.
> 
> I see:
> 
> - index=None = auto-detect
>   index=True = include the index
>   index=False = hide the index
> 
> - start=(0,0) = starting cursor position (very useful for debugging data)
> 
> Other stuff that we should consider for the documentation?

I also see fixed_header and fixed_column (both booleans) to control the
current ability to set the first row/column as fixed.

To recap, some pseudocode:

  pd.view(data, index=None, start=None,
          fixed_header=True, fixed_column=None, **kwargs)
    if index is None:
      index = data.has_index()
    if fixed_column is None:
      fixed_column = index
    data = data.to_list()
    return pd.view_list(data, start,
                       fixed_header, fixed_column, **kwargs)

  pd.view_list(data, start=None,
               fixed_header=True, fixed_column=False, **kwargs)
    # data is a list of lists
    # start should be an X,Y tuple
    ...
    # call tableview here

Scott, if I didn't bore you to death yet, I wanted to drag you in this,
since view_list is what should eventually call tabview. The
start/fixed_header/fixed_column are supposed to control the display and
thus need to creep into tabview.view().

**Comment by firecat53** [comment]
Not trying to ignore you guys here....I've got some background catchup to do before I can intelligently comment!

**Comment by firecat53** [comment]
Ok, I think I see what you're asking for. To summarize:

1. Implement start_position/index (#56)
2. Implement fixed_column (#49)
3. Add fixed_header as a view() option
4. Add the start_position/index, fixed_column, and fixed_header as arguments to view()/Viewer(). 
5. Switch to the (*args, **kwargs) format for view() and run() to ease future extensibility.
6. Turning the Pandas data types into a generic list-of-lists will be patched into Pandas and not into tabview. (https://github.com/pydata/pandas/issues/9179#issuecomment-68542977)

Am I understanding correctly? :)

**Comment by wavexx** [comment]
On 01/07/2015 05:55 AM, Scott Hansen wrote:
> Ok, I think I see what you're asking for. To summarize:
> 
> 1. Implement start_position/index (#56)
> 2. Implement fixed_column (#49)
> 3. Add fixed_header as a view() option
> 4. Add the start_position/index, fixed_column, and fixed_header as arguments to view()/Viewer(). 
> 5. Switch to the (*args, **kwargs) format for view() and run() to ease future extensibility.

You don't need this point actually, this is just an internal detail of
the pandas framework to support any viewer, not just tabview.

The idea is to offer though a minimal set of parameters that a viewer
should implement.

> 6. Turning the Pandas data types into a generic list-of-lists will be
> patched into Pandas and not into tabview.
> (https://github.com/pydata/pandas/issues/9179#issuecomment-68542977)

A good looking prototype is there already:

https://github.com/pydata/pandas/pull/9191/files

Just needs to pass the right parameters to tabview.

**Comment by scls19fr** [comment]
Hello,

sorry guys I'm very busy these days.

about start_position it will be nice if it could be either a number (number of line - column set to 1) or a tuple (number of line and number of column)

    try:
        (row, col) = start_position
    except:
        (start_position, 1) = start_position

Kind regards

**Comment by wavexx** [comment]
On 01/07/2015 12:11 PM, scls19fr wrote:
> Hello,
> 
> sorry guys I'm very busy these days.
> 
> about start_position it will be nice if it could be either a number (number of line - column set to 1) or a tuple (number of line and number of column)
> 
>     try:
>         (row, col) = start_position
>     except:
>         (start_position, 1) = start_position

Very good suggestion.

**Comment by firecat53** [comment]
Please check the 'start_pos' branch for implementation of the starting cursor position.

**Comment by firecat53** [comment]
Closing this PR. PR #116 is adressing Pandas compatibility.

**Pull request closed without merging**
