### PR TITLE
Fix search

### PR DESCRIPTION
**Pull request by wavexx**
Improved search behavior:

- use textpad.Textbox instead of getstr()
- place the cursor at a nearby location
- use goto_x/y functions

### CODE REVIEW

**Comment by firecat53** [comment]
First commit works great.

I was attempting today to implement general next/prev result functions that would emulate vim (jump to closest result). Works...but was _really_ slow, even on a small file. <sigh> back to the drawing board.

**Comment by wavexx** [comment]
On 01/05/2015 04:20 AM, Scott Hansen wrote:
> I was attempting today to implement general next/prev result
> functions that would emulate vim (jump to closest result).
> Works...but was _really_ slow, even on a small file. <sigh> back to
> the drawing board.

Shouldn't be slower than before though. no?

The 2nd commit is indeed a bit of a hack, since I would prefer search to
be just to the next occurrence if we're not showing the total number of
matches (that is: iterate from the cursor location, not from the start).

A wrap-around notice like vim would also be a very good idea.

**Comment by firecat53** [comment]
I'm very close to having a working incremental search....FYI :smile:

**Comment by firecat53** [comment]
And a first crack at incremental search done in the 'textbox' branch. No unicode text entry yet...

**Comment by wavexx** [comment]
On 02/21/2015 02:30 AM, Scott Hansen wrote:
> And a first crack at incremental search done in the 'textbox' branch.
> No unicode text entry yet...

Ah yes, very nice work. Also on the Help front, I think I couldn't see
the entire help since a couple of weeks already ;)

Also I see the refresh issue is gone.
It still doesn't redraw properly when resized, but this is a minor issue
IMHO. It's already much better than what we have on master.

**Comment by firecat53** [comment]
Cool! I'll go ahead and push my changes. Included in part in 1.4.0

**Pull request closed without merging**
